### ISSUE TITLE
.gitignore references unyson theme

### ISSUE THREAD

**Issue by lrdiv** [kohactive/stump-cli#7]
Right now a unyson theme seems to be hardcoded in the generated .gitignore file. The file should be dynamic and reference the theme name entered during the stump-cli init.

**Comment by andimal** [comment]
I added it as an issue on the [stump repo](https://github.com/kohactive/stump/issues/5) because I'd like to separate these asap

**Comment by lrdiv** [comment]
@andimal I submitted a PR for this repo that uses tilt in the init process and re-writes the gitignore. Let me know what you think.

**Comment by lrdiv** [comment]
@andimal I see what you mean about separating the stump theme outside of the wp core. That is probably a better solution.
